kind: Deployment
apiVersion: apps/v1
metadata:
  name: utility
  labels:
    app: utility
    app.kubernetes.io/component: utility
    app.kubernetes.io/instance: utility
spec:
  replicas: 0
  selector:
    matchLabels:
      deployment: utility
  template:
    metadata:
      labels:
        deployment: utility
    spec:
      volumes:
        - name: labelstud-pvc
          persistentVolumeClaim:
            claimName: labelstud-pvc
      containers:
        - name: utility
          image: registry.access.redhat.com/ubi9:latest
          command:
            - sleep
            - infinity
          volumeMounts:
            - name: labelstud-pvc
              mountPath: /opt/app-root/src/.local
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
